apiVersion: v1
kind: Secret
metadata:
  name: cloud-demo-secret
  namespace: cloud-demo
type: Opaque
stringData:
  JWT_SECRET: volunteerPlatformSecretKey2024
  CLOUD_DEMO_JWT_SECRET: volunteerPlatformSecretKey2024ForJWTTokenGeneration
  MYSQL_ROOT_PASSWORD: "123888"
  USER_SERVICE_DB_PASSWORD: "123888"
  ACTIVITY_SERVICE_DB_PASSWORD: "123888"
  ANNOUNCEMENT_SERVICE_DB_PASSWORD: "123888"
  FEEDBACK_SERVICE_DB_PASSWORD: "123888"
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  MINIO_ACCESS_KEY: root
  MINIO_SECRET_KEY: "12345678"
  SPRING_DATA_REDIS_PASSWORD: ""
  DEEPSEEK_API_KEY: ""
