spring.application.name=gateway-service
server.port=9000
server.address=0.0.0.0

# Nacos 注册中心
spring.cloud.nacos.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.fail-fast=false

# Gateway路由配置
# 用户服务路由
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

# 活动服务路由
spring.cloud.gateway.routes[1].id=activity-service
spring.cloud.gateway.routes[1].uri=lb://activity-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/activity/**

# 跨域配置
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# JWT配置
jwt.secret=volunteerPlatformSecretKey2024
jwt.expiration=86400000

logging.file.name=${APP_LOG_FILE:../../gateway-service/logs/debug.log}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} traceId=%X{traceId} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} traceId=%X{traceId} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=15
logging.logback.rollingpolicy.total-size-cap=1GB
logging.level.root=INFO
logging.level.org.example=INFO
logging.level.com.alibaba.nacos=WARN
